### PR TITLE
Migrate i18n

### PR DESCRIPTION
**Pull request by lycc193**
Due to the relatively standardized formatting, the migration of i18n format was accomplished relatively easily through a script-like approach.
The naming of keys was based on the arrangement of the existing format. For ease of modification, the submissions were split into different parts.
Only a simple proofreading was conducted, so perfect migration is not guaranteed (but there should be no issues). At the same time, some existing bugs were fixed (see some comments).
After the migration, an in-game real-machine test was conducted. Due to game progress issues, there may be some unfinished migrations for parts of the game that I haven't reached yet, which will require your testing. The multi-language feature can run normally (but only loading and display were tested, without translation).
There are still some detailed issues that have not been migrated, such as `Mod.instance.CastDisplay`, etc. 
Also, since I only have access to version 3.0.1, the merging work between versions will need to be handled by you.
(Generated by GPT, and relevant issues were discussed in the DC group several months ago.)

### CODE REVIEW

**Comment by Neosinf** [comment]
Thanks for your hard work regarding the migration to i18n, though perhaps we could have discussed this further before you went ahead? When I have time I will review the changes you've requested. How much time did this take you?

**Comment by lycc193** [comment]
In fact, it didn't take long. Less than 20 hours in total.

**Comment by Neosinf** [comment]
i hope that's a typo - 20 hours seems like you manually formatted every string

**Comment by lycc193** [comment]
The main issue is about the effectiveness of in-game migration and the verification of keys.
Also, in fact, I did the migration work twice. Initially, I didn't consider splitting the commits, but later, I cleaned up the commit content and refactored the key structure to make the review process more convenient.

**Comment by lycc193** [comment]
It would be best if you have an update plan, but I'm just showing an alternative here. I just want to point out that the migration cost is not very high.
Regarding this discussion, perhaps it's not quite suitable in the dc group (?)
Also, I found some bugs during the migration process. should I open a new issue to record them?

**Comment by Neosinf** [comment]
I'll create a channel for translation on the server and invite you. Yea send as many bug reports as you want lol.

**Pull request closed without merging**
